version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-northeast-1)
  build:
    commands:
      - echo Building the frotnend Docker image...
      - docker build -t share-post-frontend:latest ./frontend/
      - docker tag share-post-frontend:latest 384382957544.dkr.ecr.ap-northeast-1.amazonaws.com/share-post-frontend:latest
 

      - echo building the backend docker image...
      - docker build -t share-post-backend:latest ./backend/
      - docker tag share-post-backend:latest  384382957544.dkr.ecr.ap-northeast-1.amazonaws.com/share-post-backend:latest


  post_build:
    commands:
      - echo Pushing the frontend Docker image...
      - docker push 384382957544.dkr.ecr.ap-northeast-1.amazonaws.com/share-post-frontend:latest

      - echo Pushing the backend docker image...
      - docker push 384382957544.dkr.ecr.ap-northeast-1.amazonaws.com/share-post-backend:latest

      - echo Writing image definitions file...
      - printf '[{"name":"{frontend}","imageUri":"%s"}, {"name":"{backend}", "imageUri":"%s"}]' 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-frotnend:latest 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-backend:latest> imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
