version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the frotnend Docker image...
      - docker image build --file Dockerfile ./frontend/ -t share-post-frontend:latest
      - docker tag share-post-frontend:latest 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-frontend:latest

      - echo building the backend docker image...
      - docker image build --file Dockerfile ./backend/ -t share-post-backend:latest
      - docker tag share-post-backend:latest 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-backend:latest

  post_build:
    commands:
      - echo Pushing the frontend Docker image...
      - docker push 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-frontend:latest

      - echo Pushing the backend docker image...
      - docker push 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-backend:latest

      - echo Writing image definitions file...
      - printf '[{"name":"{frontend}","imageUri":"%s"}, {"name":"{backend}", "imageUri":"%s"}]' 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-frotnend:latest 384382957544.dkr.ecr.us-east-1.amazonaws.com/share-post-backend:latest> imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
