version: '3'

services:
  share-pos-db:
    build: ./database
    container_name: share-pos-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  share-pos-backend:
    build: ./backend
    container_name: share-pos-backend
    ports:
      - 8080:8080
    
  share-pos-frontend:
    build: ./frontend
    container_name: share-pos-frontend
    tty: true
    ports:
      - 3000:3000

